[package]
name = "michuhu"
version = "0.1.0"
authors = ["storyfeet <thebeaky@psmail.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
#
[lib]
path="src/lib.rs"
name="michuhu_lib"

[[bin]]
path="src/main.rs"
name="michuhu"

[dependencies]
gobble = {path="../../mlibs/gobble/"}
anyhow = "1.0.31"
